<a href="https://colab.research.google.com/github/ashutoshgithubs/Machine-Learning/blob/main/fakeNewsClassifierUsingLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
import pandas as pd

In [116]:
df = pd.read_csv('/content/fake_train.csv',
                 engine='python',
                 encoding='utf-8',
                 quotechar='"',
                 skipinitialspace=True,
                 on_bad_lines='skip')

In [117]:
df.head()

id                                              title              author  \
0  0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1  1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2  2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3  3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4  4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...     1  
1  Ever get the feeling your life circles the rou...     0  
2  Why the Truth Might Get You Fired October 29, ...     1  
3  Videos 15 Civilians Killed In Single US Airstr...     1  
4  Print \nAn Iranian woman has been sentenced to...     1

In [118]:
df.shape

(20822, 5)

In [119]:
df.isnull().sum()

id           0
title      565
author    1975
text       135
label       22
dtype: int64

In [120]:
# Drop Nan Values
df=df.dropna()

In [121]:
df.head()

id                                              title              author  \
0  0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1  1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2  2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3  3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4  4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...     1  
1  Ever get the feeling your life circles the rou...     0  
2  Why the Truth Might Get You Fired October 29, ...     1  
3  Videos 15 Civilians Killed In Single US Airstr...     1  
4  Print \nAn Iranian woman has been sentenced to...     1

In [122]:
df.shape

(18212, 5)

In [123]:
# Lets get independent feature. Here Label is dependent feature so I drop Label
# from df to get independent features
X = df.drop('label', axis=1)

In [124]:
X.head()

id                                              title              author  \
0  0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1  1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2  2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3  3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4  4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [125]:
# Lets get dependent features
y = df['label']

In [126]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20817    0
20818    0
20819    0
20820    1
20821    1
Name: label, Length: 18212, dtype: object

In [127]:
import tensorflow as tf

In [128]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [129]:
# Vocabulary size
voc_size=5000

### One Hot Representation




In [130]:
messages = X.copy()

In [131]:
print(len(messages))

18212


In [132]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [133]:
messages.reset_index(inplace=True)

In [134]:
messages.head()

index id                                              title  \
0      0  0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1  1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2  2                  Why the Truth Might Get You Fired   
3      3  3  15 Civilians Killed In Single US Airstrike Hav...   
4      4  4  Iranian woman jailed for fictional unpublished...   

               author                                               text  
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...  
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...  
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...  
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...  
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...

### Text preprocessing

In [135]:
import nltk
import re
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [136]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [137]:
corpus=[]
for i in range(0,len(messages)):
  text_clean = text_clean = re.sub(r'[^a-zA-Z\s]', "", messages['title'][i])
  lower_text = text_clean.lower()
  tolenized_text = word_tokenize(lower_text)
  stemmed_word = []
  for word in tolenized_text:
    if not word in stopwords.words('english'):
      words = ps.stem(word)
      stemmed_word.append(words)

  review = ' '.join(stemmed_word)
  corpus.append(review)

In [138]:
corpus

['hous dem aid didnt even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'benot hamon win french socialist parti presidenti nomin new york time',
 'backchannel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soroslink indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close

In [139]:
# Here text is cleaned. Now OHE is applied
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[3608, 1019, 4561, 3333, 4373, 4623, 1173, 690, 3423, 4863, 2227],
 [2660, 3944, 2571, 2390, 1248, 381, 2825],
 [197, 1599, 2226, 267],
 [2240, 1146, 3386, 4569, 2496, 1149],
 [1303, 1248, 15, 2613, 97, 322, 1248, 2546, 231, 4083],
 [4004,
  4363,
  1553,
  2625,
  1181,
  2402,
  1319,
  168,
  2511,
  3109,
  3461,
  3623,
  4273,
  4663,
  2825],
 [2754, 4547, 218, 252, 4690, 685, 3603, 4148, 148, 3584, 2797],
 [2998, 2514, 2633, 4709, 3646, 2402, 4942, 148, 3584, 2797],
 [72, 3839, 1810, 3852, 431, 3809, 1721, 2402, 3916],
 [3661, 4188, 1044, 3813, 2411, 3623, 3838, 704],
 [1388, 1571, 2660, 2810, 1167, 4195, 4107, 4208, 2497, 12, 1671],
 [4569, 3407, 4623, 4518, 2402, 4709],
 [3034, 3744, 50, 1331, 1210, 4135, 123, 2933, 4322],
 [4413, 189, 4060, 2976, 3455, 2326, 2706, 148, 3584, 2797],
 [921, 4609, 4061, 832, 2863, 148, 3584, 2797],
 [3013, 4486, 2391, 762, 1885, 2579, 1930, 3490, 2485, 1395],
 [4969, 4124, 3944],
 [1366, 4704, 2811, 4520, 2402, 1248, 3155, 2825],
 [37, 2854, 2

### Embedding Representation

In [140]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3608 1019 4561 ...    0    0    0]
 [2660 3944 2571 ...    0    0    0]
 [ 197 1599 2226 ...    0    0    0]
 ...
 [ 653 4598 2568 ...    0    0    0]
 [4180 4709 3384 ...    0    0    0]
 [4585  817 1890 ...    0    0    0]]


In [141]:
## Creating model
embedding_vector_features=40 # Each word is represented as a vector of size 40.
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid')) #This adds a dense (fully connected) output layer with one unit and a sigmoid activation function.
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [142]:
model.predict(embedded_docs)
#In the above cell I have defined and compiled the model, and then immediately used model.predict(embedded_docs) in this cell.
# Since the model hasn't been trained yet using fit(), the predictions I am seeing are essentially random outputs
# from an uninitialized model.

570/570 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step


array([[0.5066515 ],
       [0.5066285 ],
       [0.50653696],
       ...,
       [0.50613403],
       [0.5065316 ],
       [0.5065128 ]], dtype=float32)

In [143]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (32, 20, 40)           │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (32, 100)              │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (32, 1)                │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

### Lets convert the embedded_docs and y from list to numpy array
###### Converting your data to NumPy arrays is a standard and best practice when working with deep learning models in Python due to the performance, memory efficiency, and compatibility benefits.

In [144]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [145]:
X_final

array([[3608, 1019, 4561, ...,    0,    0,    0],
       [2660, 3944, 2571, ...,    0,    0,    0],
       [ 197, 1599, 2226, ...,    0,    0,    0],
       ...,
       [ 653, 4598, 2568, ...,    0,    0,    0],
       [4180, 4709, 3384, ...,    0,    0,    0],
       [4585,  817, 1890, ...,    0,    0,    0]], dtype=int32)

In [146]:
y_final

array(['1', '0', '1', ..., '0', '1', '1'], dtype=object)

### Model Training

In [162]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [161]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

ValueError: Invalid dtype: object