<a href="https://colab.research.google.com/github/ashutoshgithubs/Machine-Learning/blob/main/fakeNewsClassifierUsingLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('/content/fake_train.csv',
                 engine='python',
                 encoding='utf-8',
                 quotechar='"',
                 skipinitialspace=True,
                 on_bad_lines='skip')

In [12]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [13]:
df.shape

(194, 5)

In [14]:
df.isnull().sum()

id         0
title      4
author    20
text       3
label      0
dtype: int64

In [15]:
# Drop Nan Values
df=df.dropna()

In [16]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [17]:
df.shape

(168, 5)

In [18]:
# Lets get independent feature. Here Label is dependent feature so I drop Label
# from df to get independent features
X = df.drop('label', axis=1)

In [19]:
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [20]:
# Lets get dependent features
y = df['label']

In [21]:
y

0      1
1      0
2      1
3      1
4      1
      ..
189    1
190    1
191    0
192    1
193    1
Name: label, Length: 168, dtype: int64

In [22]:
import tensorflow as tf

In [23]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [24]:
# Vocabulary size
voc_size=5000

### One Hot Representation




In [25]:
messages = X.copy()

In [26]:
print(len(messages))

168


In [27]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [28]:
messages.reset_index(inplace=True)

In [29]:
messages.head()

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text  
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...  
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...  
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...  
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...  
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...

### Text preprocessing

In [30]:
import nltk
import re
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [31]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [32]:
corpus=[]
for i in range(0,len(messages)):
  text_clean = text_clean = re.sub(r'[^a-zA-Z\s]', "", messages['title'][i])
  lower_text = text_clean.lower()
  tolenized_text = word_tokenize(lower_text)
  stemmed_word = []
  for word in tolenized_text:
    if not word in stopwords.words('english'):
      words = ps.stem(word)
      stemmed_word.append(words)

  review = ' '.join(stemmed_word)
  corpus.append(review)

In [33]:
corpus

['hous dem aid didnt even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'benot hamon win french socialist parti presidenti nomin new york time',
 'backchannel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soroslink indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close

In [34]:
# Here text is cleaned. Now OHE is applied
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[1824, 4616, 2913, 1073, 1552, 616, 3201, 3682, 3905, 3159, 927],
 [4348, 3214, 2020, 2941, 3593, 1975, 62],
 [4914, 3666, 2971, 1510],
 [1757, 1438, 1602, 381, 4529, 1112],
 [3146, 3593, 80, 1070, 1352, 1590, 3593, 313, 2960, 4796],
 [4564,
  4702,
  1691,
  3763,
  4569,
  1141,
  1544,
  155,
  4188,
  3250,
  3379,
  3865,
  888,
  1618,
  62],
 [968, 3433, 4567, 4503, 2179, 3578, 4665, 2027, 799, 4522, 4316],
 [1432, 1806, 3455, 311, 3827, 1141, 4369, 799, 4522, 4316],
 [3443, 4593, 1238, 2896, 2640, 4910, 2310, 1141, 1989],
 [2084, 2160, 3079, 3033, 434, 193, 3545, 3839],
 [3185, 4175, 1194, 971, 2162, 3757, 224, 3549, 4807, 4718, 743],
 [381, 289, 616, 1052, 1141, 311],
 [1144, 134, 4436, 461, 4195, 4290, 3009, 854, 1677],
 [3315, 3117, 1275, 913, 1443, 3612, 2250, 799, 4522, 4316],
 [3609, 4520, 3708, 2900, 2421, 799, 4522, 4316],
 [3846, 850, 3740, 1218, 4821, 1544, 330, 4363, 2813, 2096],
 [884, 657, 3214],
 [1719, 400, 3341, 615, 1141, 3330, 637, 62],
 [2307, 632, 2020, 248

### Embedding Representation

In [44]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3905 3159  927]
 [   0    0    0 ... 3593 1975   62]
 [   0    0    0 ... 3666 2971 1510]
 ...
 [   0    0    0 ...  799 4522 4316]
 [   0    0    0 ...  782 2915 2020]
 [   0    0    0 ... 2317 3050 4613]]


In [45]:
## Creating model
embedding_vector_features=40 # Each word is represented as a vector of size 40.
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid')) #This adds a dense (fully connected) output layer with one unit and a sigmoid activation function.
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [46]:
model.predict(embedded_docs)
#In the above cell I have defined and compiled the model, and then immediately used model.predict(embedded_docs) in this cell.
# Since the model hasn't been trained yet using fit(), the predictions I am seeing are essentially random outputs
# from an uninitialized model.

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step


array([[0.5002737 ],
       [0.50147164],
       [0.50339353],
       [0.50308335],
       [0.49860555],
       [0.50141823],
       [0.49852446],
       [0.49855006],
       [0.50265867],
       [0.4992363 ],
       [0.50170386],
       [0.49924427],
       [0.49828303],
       [0.49685946],
       [0.49593064],
       [0.50522876],
       [0.4997782 ],
       [0.5004973 ],
       [0.49712968],
       [0.49762025],
       [0.4976942 ],
       [0.49631417],
       [0.4977251 ],
       [0.5008292 ],
       [0.49906433],
       [0.4985    ],
       [0.4970721 ],
       [0.4990389 ],
       [0.50033647],
       [0.49637592],
       [0.4964206 ],
       [0.50285614],
       [0.5005306 ],
       [0.4985834 ],
       [0.49788463],
       [0.49834293],
       [0.49810958],
       [0.49948713],
       [0.4968985 ],
       [0.4969362 ],
       [0.5041095 ],
       [0.49844933],
       [0.5044023 ],
       [0.5019809 ],
       [0.5005462 ],
       [0.4998064 ],
       [0.5022266 ],
       [0.498

In [47]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (32, 20, 40)           │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (32, 100)              │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (32, 1)                │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

### Lets convert the embedded_docs and y from list to numpy array
###### Converting your data to NumPy arrays is a standard and best practice when working with deep learning models in Python due to the performance, memory efficiency, and compatibility benefits.

In [48]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [49]:
X_final

array([[   0,    0,    0, ..., 3905, 3159,  927],
       [   0,    0,    0, ..., 3593, 1975,   62],
       [   0,    0,    0, ..., 3666, 2971, 1510],
       ...,
       [   0,    0,    0, ...,  799, 4522, 4316],
       [   0,    0,    0, ...,  782, 2915, 2020],
       [   0,    0,    0, ..., 2317, 3050, 4613]], dtype=int32)

In [50]:
y_final

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1])

### Model Training

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [52]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 3s 472ms/step - accuracy: 0.6057 - loss: 0.6910 - val_accuracy: 0.6429 - val_loss: 0.6806
Epoch 2/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.5744 - loss: 0.6792 - val_accuracy: 0.6429 - val_loss: 0.6695
Epoch 3/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.5952 - loss: 0.6654 - val_accuracy: 0.6429 - val_loss: 0.6549
Epoch 4/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.5952 - loss: 0.6475 - val_accuracy: 0.6429 - val_loss: 0.6365
Epoch 5/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.5952 - loss: 0.6249 - val_accuracy: 0.6429 - val_loss: 0.6139
Epoch 6/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - accuracy: 0.6124 - loss: 0.5950 - val_accuracy: 0.6786 - val_loss: 0.5873
Epoch 7/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.6771 - loss: 0.5614 - val_accuracy: 0.8036 - val_loss: 0.5583
Epoch 8/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 0.9271 - loss: 0.5174 - val_accuracy: 0.8393 - val_loss: 0

### Adding Dropout

In [54]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))# During training, this layer will randomly set 30% of the input units to zero.
model.add(LSTM(100))
model.add(Dropout(0.3)) #it randomly sets 30% of the output units from the LSTM layer to zero during training, further reducing overfitting.
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


### Performance Metrics And Accuracy

In [70]:
y_pred = model.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


In [71]:
y_pred

array([[0.5012126 ],
       [0.50025016],
       [0.5018759 ],
       [0.50100565],
       [0.49843666],
       [0.5017276 ],
       [0.50051606],
       [0.500352  ],
       [0.50131273],
       [0.5003335 ],
       [0.5005802 ],
       [0.50158715],
       [0.50093937],
       [0.5006292 ],
       [0.50052845],
       [0.50059766],
       [0.50079834],
       [0.4991123 ],
       [0.50140774],
       [0.49992943],
       [0.5006341 ],
       [0.49928796],
       [0.5003108 ],
       [0.4989546 ],
       [0.5010203 ],
       [0.5012397 ],
       [0.5012483 ],
       [0.4996899 ],
       [0.5005189 ],
       [0.50329375],
       [0.5024836 ],
       [0.4985878 ],
       [0.501053  ],
       [0.49963468],
       [0.5003512 ],
       [0.50122297],
       [0.5031749 ],
       [0.50048274],
       [0.49991125],
       [0.5016163 ],
       [0.49820203],
       [0.5005828 ],
       [0.498735  ],
       [0.50155246],
       [0.5013524 ],
       [0.5007393 ],
       [0.5003242 ],
       [0.499

In [72]:
y_pred=np.where(y_pred > 0.5, 1,0)

In [73]:
y_pred

array([[1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [60]:
y_test

array([0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0])

In [74]:
from sklearn.metrics import confusion_matrix

In [75]:
confusion_matrix(y_test,y_pred)

array([[ 5, 31],
       [ 7, 13]])

In [76]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.32142857142857145

In [77]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.42      0.14      0.21        36
           1       0.30      0.65      0.41        20

    accuracy                           0.32        56
   macro avg       0.36      0.39      0.31        56
weighted avg       0.37      0.32      0.28        56

