<a href="https://colab.research.google.com/github/ashutoshgithubs/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy - Numerical Python

---
1. Allow several mathematical operations
2. Faster operations



In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
my_list = [];
n = int(input("Enter size of list: "))
for i in range(n):
  inp = int(input("Enter element:"))
  my_list.append(inp)
print(my_list)

Enter size of list: 3
Enter element:1
Enter element:2
Enter element:3
[1, 2, 3]


In [ ]:
list1 = list(range(100))
print(list1)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


## Comapring time of execution of a list and a numpy

In [ ]:
my_list1 = list(range(10000))
start_time = process_time()
my_list1 = [i+5 for i in my_list1] # we can also write this line using for loop by creating a new list and appending the values from old list
end_time = process_time()
print(end_time - start_time)

0.0007102379999999187


In [ ]:
new_list = [i for i in range(10)]
print(new_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# Now doing the above using numpy

np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array+=5
end_time = process_time()
print(end_time - start_time)

0.0010704879999998695


## Different Operations on numpy

In [ ]:
a = np.array([1,2,3,4]) # By default dtype is integer
print(a)
a.shape   # tells the size of the matrix. Here it has 4 col and 1 row

[1 2 3 4]


(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)], dtype= float)
print(b)
b.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

## Initial Placeholder in numpy array

In [ ]:
x = np.zeros((3,4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
y = np.ones((3,4)) # Here one will be floating points
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
z = np.full((3,3),6) # here all values will be 6
print(z)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
# Indentity matrix where all digonal elements are 1
p = np.eye(3,dtype=int)
print(p)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# Creating a Numpy array with random values
import numpy as np
rand_array = np.random.random((3,4))
print(rand_array) #print values ranging from 0 to 1

[[0.11573797 0.80028037 0.56839764 0.23403326]
 [0.23679739 0.39801797 0.37583211 0.92420585]
 [0.22813394 0.45987856 0.96688196 0.10657941]]


In [ ]:
# Creating a Numpy array with specific random values
newRand_arr = np.random.randint(10,100,(3,5))
print(newRand_arr)

[[41 40 69 14 64]
 [26 72 55 52 72]
 [83 14 55 56 58]]


In [ ]:
# Array of evenly spaced values -> specifying the number of values required
d = np.linspace(10,40,6) # gives 6 values between 10 to 40 with evenly spaced
print(d)

[10. 16. 22. 28. 34. 40.]


In [ ]:
# Array of evenly spaced values -> specifying the steps
e = np.arange(10,40,6) # gives values between 10 to 40 with space = 6
print(e)

[10 16 22 28 34]


In [ ]:
# Conerting a list to numpy array
list3 = [1,2,3,4]
np_arr = np.asarray(list3)
print(np_arr)
type(np_arr)

[1 2 3 4]


numpy.ndarray

## Analysing numpy array

In [ ]:
num_arr = np.random.randint(10,100,(3,5))
print(num_arr)

[[56 57 86 17 35]
 [75 78 32 60 75]
 [28 27 14 88 16]]


In [ ]:
# FInding no of rows and col
print(num_arr.shape)

(3, 5)


In [ ]:
# Finding dimension of array whether its a 2D or 3D
print(num_arr.ndim)

2


In [ ]:
# FInding the number of elements in the arrat
print(num_arr.size)

15


In [ ]:
# Finding the data type of the array
print(num_arr.dtype)

int64


## Mathematical operations on numpy array

In [ ]:
l1 = [1,2,3]
l2 = [4,5,6]
print(l1+l2) # List here perform concatenation not add operation

[1, 2, 3, 4, 5, 6]


In [ ]:
np1 = np.random.randint(0,10,(3,3))
np2 = np.random.randint(10,20,(3,3))
print(np1)
print(np2)

[[0 6 8]
 [6 4 9]
 [6 9 7]]
[[10 14 14]
 [19 11 13]
 [13 13 14]]


In [ ]:
print(np.add(np1,np2)) # we can also write print(np1+np2)
print(np.subtract(np1,np2))
print(np.multiply(np1,np2))
print(np.divide(np1,np2))

[[10 20 22]
 [25 15 22]
 [19 22 21]]
[[-10  -8  -6]
 [-13  -7  -4]
 [ -7  -4  -7]]
[[  0  84 112]
 [114  44 117]
 [ 78 117  98]]
[[0.         0.42857143 0.57142857]
 [0.31578947 0.36363636 0.69230769]
 [0.46153846 0.69230769 0.5       ]]


## Array Manipulation

In [ ]:
r1 = np.random.randint(0,10,(3,4))
print(r1)
print(r1.shape)

[[5 1 8 5]
 [9 5 9 0]
 [7 3 8 8]]
(3, 4)


In [ ]:
# Transpose of r1
print(np.transpose(r1)) # ALso we can write : trans = r1.T
print(np.transpose(r1).shape)

[[5 9 7]
 [1 5 3]
 [8 9 8]
 [5 0 8]]
(4, 3)
