<a href="https://colab.research.google.com/github/ashutoshgithubs/Machine-Learning/blob/main/wordEmbeddingTech.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras
#### Steps:


*   Sentence
*   One Hot Encoding
*   Padding (post/pre) -> OHE
*   OHE -> Vector





In [1]:
!pip install tensorflow[and-cuda]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.3/363.3 MB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 93.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 83.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 895.7/895.7 kB 46.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 577.2/577.2 MB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.5/192.5 MB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.3/130.3 MB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 217.6/217.6 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.0/199.0 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 34.0 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.6.85
    Uninstalli

In [2]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences /corpus
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [8]:
### Vocabulary size
voc_size=500

### OHE Representation

In [6]:
ohe_rep = []
for words in sent:
  one_hot_rep = one_hot(words, voc_size)
  ohe_rep.append(one_hot_rep)

In [7]:
ohe_rep

[[35, 34, 132, 333],
 [35, 34, 132, 132],
 [35, 395, 132, 65],
 [493, 494, 266, 116, 82],
 [493, 494, 266, 116, 229],
 [208, 35, 52, 132, 414],
 [483, 433, 92, 116]]

### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding # word2Vec like
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
# Lets apply pre-padding to make all sentence length same
sent_length = 7 # can take any number >=len(max sentence len)
embedded_docs = pad_sequences(ohe_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[  0   0   0  35  34 132 333]
 [  0   0   0  35  34 132 132]
 [  0   0   0  35 395 132  65]
 [  0   0 493 494 266 116  82]
 [  0   0 493 494 266 116 229]
 [  0   0 208  35  52 132 414]
 [  0   0   0 483 433  92 116]]


### Feature representation

In [14]:
dim = 10 # each element of embedded docs will be represented as a vec of size 10.

In [18]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse') #This compiles the model, preparing it for training.

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.predict(embedded_docs[0]) #This method generates output predictions for the input samples in form of vec embedding..

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 317ms/step


array([[ 0.00469248, -0.01073547,  0.00895814,  0.00262933,  0.04850277,
        -0.01256697,  0.02386774,  0.00475971, -0.00091059,  0.02498451],
       [ 0.00469248, -0.01073547,  0.00895814,  0.00262933,  0.04850277,
        -0.01256697,  0.02386774,  0.00475971, -0.00091059,  0.02498451],
       [ 0.00469248, -0.01073547,  0.00895814,  0.00262933,  0.04850277,
        -0.01256697,  0.02386774,  0.00475971, -0.00091059,  0.02498451],
       [ 0.01600876,  0.01707646, -0.03869817,  0.04631675, -0.02831711,
        -0.02229309,  0.02499728, -0.01568338, -0.0382818 ,  0.03262076],
       [-0.01663733,  0.02557254, -0.03082478, -0.01626392, -0.02441312,
        -0.02011229, -0.03128134,  0.01284528,  0.04921223, -0.04507161],
       [ 0.04349952,  0.04440976, -0.04505372, -0.01226728,  0.0167048 ,
        -0.01482568,  0.04962078,  0.0367722 ,  0.04173071, -0.01740074],
       [-0.01447834,  0.04014652, -0.039384  , -0.04374974,  0.02345014,
         0.02582233, -0.02236173, -0.0096036 

In [20]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (7, 7, 10)             │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
# Lets predict the entire embedded docs
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step


array([[[-0.00075148,  0.00397871, -0.01305057, -0.014066  ,
         -0.01240871,  0.0188851 ,  0.01685417,  0.03079201,
          0.04095152,  0.03399625],
        [-0.00075148,  0.00397871, -0.01305057, -0.014066  ,
         -0.01240871,  0.0188851 ,  0.01685417,  0.03079201,
          0.04095152,  0.03399625],
        [-0.00075148,  0.00397871, -0.01305057, -0.014066  ,
         -0.01240871,  0.0188851 ,  0.01685417,  0.03079201,
          0.04095152,  0.03399625],
        [ 0.02164781,  0.04977408, -0.03929586, -0.0015509 ,
          0.04000889,  0.03436973,  0.03555692, -0.0476131 ,
          0.01174231, -0.01067797],
        [ 0.03201317, -0.0369992 ,  0.02483188, -0.02912866,
          0.01881379, -0.03695338,  0.04551147, -0.03383148,
         -0.01536794, -0.00188925],
        [-0.02471271, -0.02866468, -0.02865238, -0.01798248,
         -0.03950733, -0.03802934, -0.01687471, -0.03290422,
          0.02990263, -0.02294538],
        [ 0.01687102,  0.0471635 , -0.0387177 ,  0.0