<a href="https://colab.research.google.com/github/ashutoshgithubs/Machine-Learning/blob/main/word2vec_%26_avgWord2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd


In [6]:
messages = pd.read_csv('/content/SMSSpamCollection.txt', sep='\t', names=["label","message"])

In [7]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
messages["message"].loc[451]

'hanks lotsly!'

# Data Cleaning and Preprocessing


*   Removing special char
*   To lowercase
*   Tokenization
*   Stemming
*   No need of Lemmatization as its span classification
*   BOW







In [5]:
!pip install nltk

In [13]:
import nltk
import re
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [14]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [15]:
corpus=[]
for i in range(0,len(messages)):
  text_clean = text_clean = re.sub(r'[^a-zA-Z\s]', "", messages["message"][i])
  lower_text = text_clean.lower()
  tolenized_text = word_tokenize(lower_text)
  stemmed_word = []
  for word in tolenized_text:
    if not word in stopwords.words('english'):
      words = ps.stem(word)
      stemmed_word.append(words)

  review = ' '.join(stemmed_word)
  corpus.append(review)




In [9]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri questionstd txt ratetc appli over',
 'u dun say earli hor u c alreadi say',
 'nah dont think goe usf live around though',
 'freemsg hey darl week word back id like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'im gon na home soon dont want talk stuff anymor tonight k ive cri enough today',
 'six chanc win cash pound txt csh send cost pday day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim tc wwwdbuknet lccltd pobox ldnwarw',
 'ive searc

## BOW Model

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

### For understanding the working of BOW

In [11]:

# Lets take a Stemmed corpus
corpus1 = ['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
          'ok lar joke wif u oni']


cv = CountVectorizer()
# BOW_MATRIX
X = cv.fit_transform(corpus1).toarray();

# Get feature names (vocabulary)->in sorted form
feature_names = cv.get_feature_names_out()
print("Vocabulary:", feature_names)
print("\nBag of Words Matrix:")
print(X)

# Show document-term mapping-> Length of each doc  = size of vocab array
print("\nDocument-Term Matrix:")
for i, doc in enumerate(corpus1):
    print(f"Document {i+1}: {doc}")
    print(f"Vector: {X[i]}")
    print()

Vocabulary: ['amor' 'avail' 'buffet' 'bugi' 'cine' 'crazi' 'go' 'got' 'great' 'joke'
 'jurong' 'la' 'lar' 'ok' 'oni' 'point' 'wat' 'wif' 'world']

Bag of Words Matrix:
[[1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0]]

Document-Term Matrix:
Document 1: go jurong point crazi avail bugi n great world la e buffet cine got amor wat
Vector: [1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 1]

Document 2: ok lar joke wif u oni
Vector: [0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0]



## Now Focus on the real work

In [12]:
cv = CountVectorizer(max_features=2500, binary = True)
X = cv.fit_transform(corpus).toarray()

In [13]:
# Vocabulary
features = cv.get_feature_names_out()
print(features)

['aah' 'aathilov' 'aathiwher' ... 'yup' 'zed' 'zoe']


In [14]:
# BOW matrix
X


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
X.shape

(5572, 2500)

In [51]:
y = pd.get_dummies(messages["label"]) # One Hot Encoding

In [52]:
y

ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [53]:
y = y.iloc[:,1].values
# Here we are taking only one column (Spam column) -> We only need ONE column for binary classification! (take ham or spam)
# Taking column 1 (spam) gives us: 1 = message is spam, 0 = message is ham

In [54]:
y


array([False, False,  True, ..., False, False, False])

### Train Test Split

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [22]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [23]:
#prediction
# Now lets supply the test msg data to predict who messaged (spam or hm) -> y_pred
y_pred=spam_detect_model.predict(X_test)

In [34]:
y_pred

array([False,  True, False, ..., False,  True, False])

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9802690582959641


In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       957
        True       0.93      0.94      0.93       158

    accuracy                           0.98      1115
   macro avg       0.96      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



## Apply TFIDF

In [36]:
# Creating the TFIDF model
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500)
X = tv.fit_transform(corpus).toarray()

In [37]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
# Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [39]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [40]:
#prediction
y_pred=spam_detect_model.predict(X_test)

In [41]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9802690582959641


In [42]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       1.00      0.98      0.99       977
        True       0.86      1.00      0.93       138

    accuracy                           0.98      1115
   macro avg       0.93      0.99      0.96      1115
weighted avg       0.98      0.98      0.98      1115



## AvgWord2Vec
 ##### Here Lemmetized word will be used

In [26]:
!pip install gensim

In [16]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [18]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [19]:
corpus2=[]
for i in range(0,len(messages)):
  text_clean = text_clean = re.sub(r'[^a-zA-Z\s]', "", messages["message"][i])
  lower_text = text_clean.lower()
  tolenized_text = word_tokenize(lower_text)
  lemmetized_word = []
  for word in tolenized_text:
    if not word in stopwords.words('english'):
      words = lemmatizer.lemmatize(word)
      lemmetized_word.append(words)
  review = ' '.join(lemmetized_word)
  corpus2.append(review)


In [21]:
corpus2

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry questionstd txt ratetcs apply over',
 'u dun say early hor u c already say',
 'nah dont think go usf life around though',
 'freemsg hey darling week word back id like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'im gon na home soon dont want talk stuff anymore tonight k ive cried enough today',
 'six chance win cash pound txt csh send cost pday day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim tc wwwdbukn

In [23]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess # to lowercase the word

In [24]:
words=[]
for sent in corpus2:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [25]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'questionstd',
  'txt',
  'ratetcs',
  'apply',
  'over'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'dont', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'id',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'sel

### Let's train Word2Vec from Scratch

In [28]:
import gensim

In [32]:
model = gensim.models.Word2Vec(words, window=5, min_count=2)

In [33]:
model.wv.index_to_key # Gives all vocabularies

['call',
 'im',
 'get',
 'ur',
 'go',
 'dont',
 'free',
 'ok',
 'ltgt',
 'know',
 'day',
 'got',
 'come',
 'like',
 'ill',
 'good',
 'time',
 'text',
 'want',
 'love',
 'send',
 'need',
 'one',
 'going',
 'today',
 'txt',
 'home',
 'lor',
 'see',
 'stop',
 'sorry',
 'still',
 'back',
 'mobile',
 'reply',
 'think',
 'take',
 'tell',
 'phone',
 'new',
 'week',
 'well',
 'hi',
 'later',
 'da',
 'please',
 'cant',
 'make',
 'night',
 'say',
 'claim',
 'thing',
 'dear',
 'much',
 'oh',
 'great',
 'hey',
 'give',
 'pls',
 'happy',
 'number',
 'na',
 'work',
 'friend',
 'hope',
 'message',
 'thats',
 'way',
 'wat',
 'msg',
 'wan',
 'prize',
 'right',
 'let',
 'min',
 'yes',
 'tomorrow',
 'already',
 'ask',
 'said',
 'yeah',
 'really',
 'amp',
 'babe',
 'life',
 'co',
 'didnt',
 'meet',
 'miss',
 'win',
 'year',
 'last',
 'morning',
 'service',
 'ive',
 'would',
 'thanks',
 'anything',
 'cash',
 'find',
 'feel',
 'lol',
 'every',
 'tone',
 'nokia',
 'sure',
 'pick',
 'care',
 'also',
 'keep',


In [34]:
# Vocabulary size
model.corpus_count

5566

In [35]:
model.epochs

5

In [36]:
model.wv.similar_by_word('list')

[('hurt', 0.9866654276847839),
 ('set', 0.9864898324012756),
 ('went', 0.9864836931228638),
 ('ill', 0.9863871335983276),
 ('sure', 0.9863761067390442),
 ('face', 0.9863753318786621),
 ('thing', 0.9863722324371338),
 ('kiss', 0.9863582849502563),
 ('xxx', 0.986356258392334),
 ('ok', 0.9863324761390686)]

### By default, this word2vec model has 100 sized dimension

In [37]:
model.wv['list'].shape

(100,)

### AvgWord2Vec

In [38]:
import numpy as np

In [59]:
def avg_word2vec(doc):
  return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key], axis=0)

In [60]:
!pip install tqdm

In [61]:
from tqdm import tqdm

In [64]:
X=[]
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))


  5%|▌         | 297/5566 [00:00<00:01, 2965.23it/s]/usr/local/lib/python3.12/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5566/5566 [00:01<00:00, 2932.41it/s]


In [65]:
X

[array([-0.14299545,  0.3067436 ,  0.0717924 ,  0.05888911,  0.02315162,
        -0.33560434,  0.0122557 ,  0.49978235, -0.1352955 , -0.17958562,
        -0.08816544, -0.32375652, -0.06059971,  0.06838539,  0.05822667,
        -0.22586243,  0.04890015, -0.346025  , -0.00966163, -0.39083815,
         0.1445847 ,  0.1501326 ,  0.11381727, -0.10527847, -0.05968306,
         0.05135117, -0.18387598, -0.2000884 , -0.19089127,  0.09497977,
         0.2356674 ,  0.05443551,  0.01026258, -0.12529804, -0.05821245,
         0.30064595,  0.06007347, -0.2515959 , -0.18265516, -0.4884688 ,
         0.04398795, -0.27412292, -0.00385346,  0.05663939,  0.18240882,
        -0.03009368, -0.18822579, -0.05289955,  0.14209366,  0.15749086,
         0.12032733, -0.21173298, -0.07088267, -0.04892315, -0.16499038,
         0.10366404,  0.09285606, -0.03649155, -0.28268462,  0.01717959,
         0.05797602,  0.12794888, -0.03717135, -0.05430404, -0.31812254,
         0.19353867,  0.09947542,  0.2534872 , -0.3

In [48]:
X[0].shape

(100,)

### Train and test the model